name: mylastfm
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

  dio: ^4.0.6
  pretty_dio_logger: ^1.1.1
  flutter_dotenv: ^5.0.2
  equatable: ^2.0.3
  bloc: ^8.0.3
  flutter_bloc: ^8.0.1
  get_it: ^7.2.0
  intl: ^0.17.0
  cached_network_image: ^3.2.0
  go_router: ^3.0.7
  flutter_html: ^2.2.1
  url_launcher: ^6.1.0
  provider: ^6.0.2
  hive: ^2.1.0
  hive_flutter: ^1.1.0
  hive_generator: ^1.1.2
  build_runner: ^2.1.10
  crypto: ^3.0.2
  google_fonts: ^2.3.2
  easy_debounce: ^2.0.2+1

  flutter_native_splash: ^2.1.6


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0


flutter_native_splash:
  color: "#ffffff"
  image: assets/splash_img.png


flutter:
  uses-material-design: true

  assets:
    - .env
